server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /api/public/   { proxy_pass http://bookservice-java-spring:8086; }
  location /api/register/ { proxy_pass http://bookservice-java-spring:8086; }
  location /api/mobile/   { proxy_pass http://bookservice-java-spring:8086; }
  location /api/barcodes/ { proxy_pass http://barcodes-go:8082; }

  location / {
    try_files $uri /index.html;
  }
}